In [12]:
import numpy as np
import pandas as pd

In [13]:
path_db = '../churn_db/ecommerce_customer_churn_dataset.csv'

In [14]:
df = pd.read_csv(path_db)
df.head()

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,Total_Purchases,Average_Order_Value,Days_Since_Last_Purchase,Discount_Usage_Rate,Returns_Rate,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,9.0,94.72,34.0,46.40,2.0,17.9,9.0,4.0,16.3,20.8,1.0,953.33,2278.0,0,Q1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,19.5,82.45,71.0,57.96,9.2,42.8,7.0,3.0,NaN,23.3,3.0,1067.47,3028.0,0,Q4
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,9.1,165.52,11.0,12.24,11.5,0.0,4.0,1.0,NaN,8.8,NaN,1289.75,2317.0,0,Q4
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,15.0,147.33,47.0,44.10,5.4,41.4,2.0,5.0,85.9,31.0,3.0,2340.92,2674.0,0,Q1
4,35.0,Male,India,Delhi,3.1,29.0,51.4,NaN,19.1,9.0,32.5,141.30,73.0,25.20,5.5,37.9,1.0,11.0,83.0,50.4,4.0,3041.29,5354.0,0,Q4

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            47505 non-null  float64
 1   Gender                         50000 non-null  object
 2   Country                        50000 non-null  object
 3   City                           50000 non-null  object
 4   Membership_Years               50000 non-null  float64
 5   Login_Frequency                50000 non-null  float64
 6   Session_Duration_Avg           46601 non-null  float64
 7   Pages_Per_Session              47000 non-null  float64
 8   Cart_Abandonment_Rate          50000 non-null  float64
 9   Wishlist_Items                 46000 non-null  float64
 10  Total_Purchases                50000 non-null  float64
 11  Average_Order_Value            50000 non-null  float64
 12  Days_Since_Last_Purchase       47000 non-null  float64
 13  Discount_Usage_Rate            46500 non-null  float64
 14  Returns_Rate                   45509 non-null  float64
 15  Email_Open_Rate                47472 non-null  float64
 16  Customer_Service_Calls         49832 non-null  float64
 17  Product_Reviews_Written        46500 non-null  float64
 18  Social_Media_Engagement_Score  44000 non-null  float64
 19  Mobile_App_Usage               45000 non-null  float64
 20  Payment_Method_Diversity       47500 non-null  float64
 21  Lifetime_Value                 50000 non-null  float64
 22  Credit_Balance                 44500 non-null  float64
 23  Churned                        50000 non-null  int64
 24  Signup_Quarter                 50000 non-null  object
dtypes: float64(20), int64(1), object(4)
memory usage: 9.5+ MB

In [16]:
df.duplicated().sum()

np.int64(0)

No duplicates

In [17]:
plt.figure(figsize=(10, 5))
age_bins = [0, 20, 30, 40, 50, 60, 70, 100]
age_labels = ['0-20', '21-30', '31-40', '41-50', '51-60', '61-70', '70+']
df['Age_Binned'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels)
sns.countplot(x='Age_Binned', data=df)
plt.title('Count Plot for Age (Binned)')
plt.show()

Age                              2495
Gender                              0
Country                             0
City                                0
Membership_Years                    0
Login_Frequency                     0
Session_Duration_Avg             3399
Pages_Per_Session                3000
Cart_Abandonment_Rate               0
Wishlist_Items                   4000
Total_Purchases                     0
Average_Order_Value                 0
Days_Since_Last_Purchase         3000
Discount_Usage_Rate              3500
Returns_Rate                     4491
Email_Open_Rate                  2528
Customer_Service_Calls            168
Product_Reviews_Written          3500
Social_Media_Engagement_Score    6000
Mobile_App_Usage                 5000
Payment_Method_Diversity         2500
Lifetime_Value                      0
Credit_Balance                   5500
Churned                             0
Signup_Quarter                      0
dtype: int64

# How to deal with null columns
Since if we remove all the null col we will be reducing the 50k rows to just 17k, so thats not a good step.

We should try to fill as many cols as we can

In [18]:
cols_with_null = df.columns[df.isnull().any()]
for col in cols_with_null:
    print(f'-----{col}----')
    print(f"Min: {df[col].min()}")
    print(f"Max: {df[col].max()}")
    print(f'median:{df[col].median()}')
    print(f'mean:{df[col].mean().round(0)}')
    print(f'25th percentil:{df[col].quantile(0.25)}')
    print(f'75th percentil:{df[col].quantile(0.75)}')
    print(f'IQR:{df[col].quantile(0.75) - df[col].quantile(0.25)}')
    print(f'Outlier: {((df[col] < df[col].quantile(0.25) - 1.5*(df[col].quantile(0.75)-df[col].quantile(0.25))) | (df[col] > df[col].quantile(0.75) + 1.5*(df[col].quantile(0.75)-df[col].quantile(0.25)))).sum()}')

-----Age----

Min: 5.0
Max: 200.0
median:38.0
mean:38.0
25th percentil:29.0
75th percentil:46.0
IQR:17.0
Outlier: 126
-----Session_Duration_Avg----
Min: 1.0
Max: 75.6
median:26.8
mean:28.0
25th percentil:19.7
75th percentil:34.7
IQR:15.000000000000004

Outlier: 300
-----Pages_Per_Session----
Min: 1.0
Max: 24.1
median:8.4
mean:9.0
25th percentil:6.0
75th percentil:11.2
IQR:5.199999999999999
Outlier: 275
-----Wishlist_Items----
Min: 0.0
Max: 28.0
median:4.0
mean:4.0
25th percentil:2.0
75th percentil:6.0
IQR:4.0
Outlier: 858
-----Days_Since_Last_Purchase----
Min: 0.0
Max: 287.0
median:21.0
mean:30.0
25th percentil:9.0
75th percentil:41.0
IQR:32.0
Outlier: 2313
-----Discount_Usage_Rate----
Min: 0.24
Max: 116.64
median:40.2
mean:42.0
25th percentil:25.3
75th percentil:57.0
IQR:31.7
Outlier: 101
-----Returns_Rate----
Min: 0.0
Max: 99.6157338622138
median:5.4
mean:7.0
25th percentil:2.9
75th percentil:9.1
IQR:6.199999999999999
Outlier: 1204
-----Email_Open_Rate----
Min: 0.0
Max: 91.7
median:19.7
mean:21.0
25th percentil:9.9
75th percentil:30.4
IQR:20.5
Outlier: 238
-----Customer_Service_Calls----
Min: 0.0
Max: 21.0
median:5.0
mean:6.0
25th percentil:4.0
75th percentil:7.0
IQR:3.0

Outlier: 1185
-----Product_Reviews_Written----
Min: 0.0
Max: 21.0
median:2.0
mean:3.0
25th percentil:1.0
75th percentil:4.0
IQR:3.0
Outlier: 1090
-----Social_Media_Engagement_Score----
Min: 0.0
Max: 100.0
median:27.6
mean:29.0
25th percentil:13.2
75th percentil:43.1
IQR:29.900000000000002
Outlier: 233
-----Mobile_App_Usage----
Min: 0.0
Max: 61.9
median:18.6
mean:19.0
25th percentil:12.5
75th percentil:25.5
IQR:13.0
Outlier: 270
-----Payment_Method_Diversity----
Min: 1.0
Max: 5.0
median:2.0
mean:2.0
25th percentil:2.0
75th percentil:3.0
IQR:1.0
Outlier: 2439
-----Credit_Balance----
Min: 0.0
Max: 7197.0
median:1896.0
mean:1966.0
25th percentil:1049.0
75th percentil:2791.0
IQR:1742.0
Outlier: 209

# Taking a quick look in the detail of each col
**Age** have many dirty values and needs to be clean [18-85]


**Returns_Rate**,Right-swek-> customer return a lot


**Days_Since_Last_Purchase**, Right sweked->many inactive users

Below can be ignored as well (low skew)

 **Customer_Service_Calls**, slight skew-> may indicate unhappy customer

 
 **Product_Reviews_Written**, slight skew-> few user write review
 
Others may have a bit of swekness, but can be ignored

In [19]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
#coerce skip null to avoid error
df.loc[(df['Age']<18) | (df['Age']>85), 'Age'] = np.nan #convert impossible val to NAN

In [20]:
pd.set_option('display.max_columns', None)
df.describe()

,Age,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,Total_Purchases,Average_Order_Value,Days_Since_Last_Purchase,Discount_Usage_Rate,Returns_Rate,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned
count,47455.000000,50000.000000,50000.000000,46601.000000,47000.000000,50000.000000,46000.000000,50000.000000,50000.000000,47000.000000,46500.000000,45509.000000,47472.000000,49832.000000,46500.000000,44000.000000,45000.000000,47500.000000,50000.000000,44500.000000,50000.000000
mean,37.763355,2.984009,11.624660,27.660754,8.737811,57.079973,4.298391,13.111576,123.117330,29.792872,41.997485,6.680913,20.937980,5.681831,2.853312,29.364466,19.371607,2.353874,1440.626292,1966.233258,0.289000
std,11.451149,2.059105,7.810657,10.871013,3.778220,16.282723,3.189754,7.017312,175.569714,29.695062,21.373642,6.143027,14.252561,2.676052,2.328948,20.574021,9.419252,1.110012,907.249443,1225.072166,0.453302
min,18.000000,0.100000,0.000000,1.000000,1.000000,0.000000,0.000000,-13.000000,26.380000,0.000000,0.240000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,29.000000,1.400000,6.000000,19.700000,6.000000,46.400000,2.000000,8.000000,87.050000,9.000000,25.300000,2.900000,9.900000,4.000000,1.000000,13.200000,12.500000,2.000000,789.817500,1049.000000,0.000000
50%,38.000000,2.500000,11.000000,26.800000,8.400000,58.100000,4.000000,12.000000,112.970000,21.000000,40.200000,5.400000,19.700000,5.000000,2.000000,27.600000,18.600000,2.000000,1243.415000,1896.000000,0.000000
75%,46.000000,4.000000,17.000000,34.700000,11.200000,68.700000,6.000000,17.000000,144.440000,41.000000,57.000000,9.100000,30.400000,7.000000,4.000000,43.100000,25.500000,3.000000,1874.000000,2791.000000,1.000000
max,75.000000,10.000000,46.000000,75.600000,24.100000,143.743350,28.000000,128.700000,9666.379178,287.000000,116.640000,99.615734,91.700000,21.000000,21.000000,100.000000,61.900000,5.000000,8987.240000,7197.000000,1.000000

In [21]:
df['Total_Purchases'] = pd.to_numeric(df['Total_Purchases'], errors='coerce')
#coerce skip null to avoid error
df.loc[(df['Total_Purchases']<0) | (df['Total_Purchases']>130), 'Total_Purchases'] = np.nan #convert impossible val to NAN

In [22]:
df=df.fillna(df.median(numeric_only=True))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            50000 non-null  float64
 1   Gender                         50000 non-null  object
 2   Country                        50000 non-null  object
 3   City                           50000 non-null  object
 4   Membership_Years               50000 non-null  float64
 5   Login_Frequency                50000 non-null  float64
 6   Session_Duration_Avg           50000 non-null  float64
 7   Pages_Per_Session              50000 non-null  float64
 8   Cart_Abandonment_Rate          50000 non-null  float64
 9   Wishlist_Items                 50000 non-null  float64
 10  Total_Purchases                50000 non-null  float64
 11  Average_Order_Value            50000 non-null  float64
 12  Days_Since_Last_Purchase       50000 non-null  float64
 13  Discount_Usage_Rate            50000 non-null  float64
 14  Returns_Rate                   50000 non-null  float64
 15  Email_Open_Rate                50000 non-null  float64
 16  Customer_Service_Calls         50000 non-null  float64
 17  Product_Reviews_Written        50000 non-null  float64
 18  Social_Media_Engagement_Score  50000 non-null  float64
 19  Mobile_App_Usage               50000 non-null  float64
 20  Payment_Method_Diversity       50000 non-null  float64
 21  Lifetime_Value                 50000 non-null  float64
 22  Credit_Balance                 50000 non-null  float64
 23  Churned                        50000 non-null  int64
 24  Signup_Quarter                 50000 non-null  object
dtypes: float64(20), int64(1), object(4)
memory usage: 9.5+ MB

## No more nulls left